# Config file for automatic testing at travis-ci.org

language: python
python:
stable
unstable
  - "2.7-stable"
  - "3.4-stable"
  - "3.5-stable"
  - "3.6-stable"
  - "2.7-stable"
  - "3.4-unstable"
  - "3.5-unstable"
  - "3.6-unstable"
# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
    - python: "3.7-stable"
      dist: xenial
      sudo: true
    - python: "3.7-unstable"
      dist: xenial
      sudo: true

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U tox-travis

# Command to run tests, e.g. python setup.py test
script: tox

# Assuming you have installed the travis-ci CLI tool, after you
# create the Github repo and add it to Travis, run the
# following command to finish PyPI deployment setup:
# $ travis encrypt --add deploy.password
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: mtmonacelli
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    repo: taylormonacelli/filesize_from_stdin
    python: 3.6
